In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Load data
data_path = r"C:\Job_og_eksamensbevis\Github\projekter\RF_project\data\creditcard_preprocessed.csv"
df = pd.read_csv(data_path)

X = df.drop('Class', axis=1).values
y = df['Class'].values

# Stratified K-Fold setup
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)


# Krydsvalidering
for fold, (train_index, test_index) in enumerate(skf.split(X, y), 1):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Træn model
    rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    rf.fit(X_train, y_train)

    # Forudsig
    y_pred = rf.predict(X_test)

    print(f"\nFold {fold}")
    print("Confusion Matrix:")
    print(conf_matrices[-1])
    print(f"Precision: {precisions[-1]:.4f}")
    print(f"Recall:    {recalls[-1]:.4f}")
    print(f"F1-score:  {f1s[-1]:.4f}")

# Gennemsnitlige metrikker
print("\n===== Gennemsnit på tværs af fold =====")
print(f"Gennemsnitlig Precision: {np.mean(precisions):.4f}")
print(f"Gennemsnitlig Recall:    {np.mean(recalls):.4f}")
print(f"Gennemsnitlig F1-score:  {np.mean(f1s):.4f}")



Fold 1
Confusion Matrix:
[[56857     6]
 [   22    76]]
Precision: 0.9268
Recall:    0.7755
F1-score:  0.8444

Fold 2
Confusion Matrix:
[[56857     6]
 [   22    76]]
Precision: 0.9268
Recall:    0.7755
F1-score:  0.8444

Fold 3
Confusion Matrix:
[[56857     6]
 [   22    76]]
Precision: 0.9268
Recall:    0.7755
F1-score:  0.8444

Fold 4
Confusion Matrix:
[[56857     6]
 [   22    76]]
Precision: 0.9268
Recall:    0.7755
F1-score:  0.8444

Fold 5
Confusion Matrix:
[[56857     6]
 [   22    76]]
Precision: 0.9268
Recall:    0.7755
F1-score:  0.8444

===== Gennemsnit på tværs af fold =====
Gennemsnitlig Precision: 0.9487
Gennemsnitlig Recall:    0.7846
Gennemsnitlig F1-score:  0.8588
